version: "3.9"

services:
  spfeas:
    # build:
    #   context: .
    #   dockerfile: dockerfile
    image: spfeas:latest
    stdin_open: true  # Keep the container's STDIN open
    tty: true         # Allocate a pseudo-TTY
    command: /bin/bash
    volumes:
      - /mnt/bigdrive/Dropbox/South_Africa_data/Projects/Agriculture_Comp/S1c_data:/mnt/
    # entrypoint: >
    #   /bin/bash -c "
    #   git clone https://github.com/mmann1123/WB-spatial-features.git /mnt/WB-spatial-features &&
    #   git clone https://github.com/mmann1123/South_Africa_Crop_Comp.git /mnt/South_Africa_Crop_Comp &&
    #   source activate spfeas &&
    #   exec /bin/bash
    #   "


 